### ISSUE TITLE
is it possible to use your template without jade?

### ISSUE THREAD

**Issue by ghost** [aderaaij/shopify-barebone-theme#1]
i love your framework but is it possible to use it without jade?

**Comment by aderaaij** [comment]
Hi there, thanks!

Right now everything is jade based, but it's really easy to remove the jade task and use the copy task to copy html files in the appropriate folders in the build directory. You can either make a new copy task or use the current one. To use the current one, add the source and build paths to the copy task in the `config.js` file and in the `tasks/copy.js` file, add a task with the right paths. 

I will try and set-up an html branch this afternoon.

**Comment by aderaaij** [comment]
edit: the branch now works with the gulp-changed plugin to make sure that only changed files will be copied to build. 

K I made a branch with just HTML templates. Right now it has the generated barebones templates in there, but if you want you can always replace them with the Skeleton theme files by placing them in the appropriate theme folders. 

The HTML version: https://github.com/aderaaij/shopify-barebone-theme/tree/shopify-barebone_html

**Comment by ghost** [comment]
thank you for your help i really appreciate it. I'll check it out asap

**Comment by aderaaij** [comment]
You're very welcome! I'm still learning a lot about shopify myself. A lot of these things you'll find in the following theme: https://github.com/aderaaij/cfye-shopify
